services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hadas091256
      MYSQL_DATABASE: travel_planner
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    command: [ "/app/wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: travel_planner
      DB_USER: root
      DB_PASS: Hadas091256
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  #  build: ./frontend
  # ports:
  #   - "3000:3000"
  #  stdin_open: true
  # tty: true
  # volumes:
  #   - ./frontend:/app
  # working_dir: /app
  # command: [ "npm", "start" ]
  # depends_on:
  #   - backend

volumes:
  mysql_data:
