services:
  backend:
    image: hadasdavid8/travelapp-backend:latest
    command: [ "/app/wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"

  frontend:
   build:
    context: ./frontend
    args:
      REACT_APP_API_BASE_URL: "/api"
      REACT_APP_GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}" 
   ports:
    - "3000:80"
   depends_on:
    - backend


volumes:
  mysql_data: