services:
  backend:
    image: hadasdavid8/travelapp-backend:latest
    command: [ "/app/wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    image: hadasdavid8/travelapp-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
