# Generated by Django 5.2.3 on 2025-07-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommender', '0002_remove_recommendedplace_photo_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itinerary.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('transport_mode', models.CharField(choices=[('WALKING', 'Walking'), ('DRIVING', 'Driving'), ('BICYCLING', 'Bicycling'), ('TRANSIT', 'Public Transit')], default='WALKING', help_text='Mode of transport to reach this place.', max_length=20)),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='itinerary.itineraryday')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.recommendedplace')),
            ],
        ),
    ]
