# Generated by Django 5.2.3 on 2025-07-13 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        ('preferences', '0002_remove_trippreferences_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='preference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='preferences.trippreferences'),
        ),
    ]
