# Generated by Django 5.2.3 on 2025-07-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text="Destination name, e.g., 'Paris' or 'Tokyo'.", max_length=255)),
                ('place_id', models.CharField(help_text='Unique Google Place ID.', max_length=150, unique=True)),
                ('name', models.CharField(help_text='Name of the place.', max_length=255)),
                ('formatted_address', models.CharField(blank=True, help_text='Formatted full address from Google.', max_length=300, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('types', models.JSONField(blank=True, help_text="List of place types/categories (e.g., ['restaurant', 'museum']).", null=True)),
                ('rating', models.FloatField(blank=True, help_text='Google rating between 0.0 and 5.0.', null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, help_text='Total number of user reviews.', null=True)),
                ('opening_hours', models.JSONField(blank=True, help_text='JSON field of opening hours if available.', null=True)),
                ('price_level', models.IntegerField(blank=True, help_text='Price level from 0 (free) to 4 (expensive).', null=True)),
                ('need_reservation', models.BooleanField(default=False, help_text='If the place typically requires reservation.')),
                ('average_visit_duration_minutes', models.IntegerField(blank=True, help_text='Estimated time people spend there, in minutes.', null=True)),
                ('photo_reference', models.CharField(blank=True, help_text='Reference string to get photo via Google Place Photos API.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this recommendation was saved.')),
            ],
        ),
    ]
