# Generated by Django 5.2.3 on 2025-07-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedplace',
            name='photo_reference',
        ),
    ]
