# Generated by Django 5.2.3 on 2025-07-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_remove_recommendedplace_photo_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedplace',
            name='html_attributions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendedplace',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
