# Generated by Django 5.2.3 on 2025-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('CULINARY', 'Culinary'), ('HISTORY', 'Historical/Cultural'), ('BEACH', 'Beach'), ('ADVENTURE', 'Adventure/Extreme'), ('NATURE', 'Nature/Hiking'), ('RELAXATION', 'Relaxation/Leisure'), ('CITY_BREAK', 'City Break'), ('ROMANTIC', 'Romantic'), ('FAMILY', 'Family'), ('LUXURY', 'Luxury'), ('BUDGET', 'Budget-friendly'), ('ART', 'Art & Galleries'), ('NIGHTLIFE', 'Nightlife'), ('WILDLIFE', 'Wildlife'), ('WINTER_SPORTS', 'Winter Sports'), ('ROAD_TRIP', 'Road Trip'), ('CRUISE', 'Cruise'), ('WELLNESS', 'Wellness/Spa')], help_text="Unique internal key for the trip style (e.g., 'CULINARY').", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name for the trip style (e.g., 'Culinary').", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Trip Style',
                'verbose_name_plural': 'Trip Styles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text="Preferred destination for the trip (e.g., 'Paris', 'Tokyo').", max_length=255)),
                ('start_date', models.DateField(blank=True, help_text='Preferred start date for the trip.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Preferred end date for the trip.', null=True)),
                ('duration', models.IntegerField(blank=True, help_text="Duration of the trip in 'days' (e.g., 7).", null=True)),
                ('participants', models.IntegerField(blank=True, help_text='Number of participants in the trip (including the user).', null=True)),
                ('pace', models.CharField(choices=[('RELAXED', 'Relaxed'), ('MODERATE', 'Moderate'), ('FAST', 'Fast/Intense')], default='MODERATE', help_text='Preferred pace of the trip.', max_length=20)),
                ('trip_styles', models.ManyToManyField(blank=True, help_text='Preferred trip style(s) (select multiple options).', to='preferences.tripstyle')),
            ],
            options={
                'verbose_name': 'Trip Preference',
                'verbose_name_plural': 'Trip Preferences',
            },
        ),
    ]
