# Generated by Django 5.2.3 on 2025-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippreferences',
            name='duration',
        ),
    ]
