name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_REPO_BACKEND: hadasdavid8/travelapp-backend
  DOCKER_HUB_REPO_FRONTEND: hadasdavid8/travelapp-frontend 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.DOCKER_HUB_REPO_BACKEND }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.DOCKER_HUB_REPO_FRONTEND }}:latest
          build-args: |
            REACT_APP_API_BASE_URL=/api
            REACT_APP_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Deploy services on server via SSH (Docker Compose)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Navigating to app directory..."
            cd /opt/TravelApp 
            echo "Pulling latest Docker images..."
            docker-compose pull
            echo "Bringing up services with Docker Compose..."
            docker-compose up -d --remove-orphans
            echo "Cleaning up old Docker images..."
            docker image prune -f 
            echo "Deployment complete."
